In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
# Load the ideal traffic patterns
loaded = open("time_distro_periodic.json")
loaded2 = open("time_distro_stochastic.json")

In [3]:
data = json.load(loaded)
data2 = json.load(loaded2)

In [4]:
chann = list(data)
chann2 = list(data2)
# print(chann)
# print(chann2)

In [5]:
def get_values(data,type1,type2):
    chann = list(data[type1][type2])
    chann = chann[::]
#     print(len(chann))
    
    return chann

periodic1 = get_values(data,"channel_five", "time_distro")
periodic2 = get_values(data,"channel_three", "time_distro")
periodic3 = get_values(data,"channel_two", "time_distro")
periodic4 = get_values(data,"channel_one", "time_distro")
periodic5 = get_values(data,"channel_four", "time_distro")
periodic6 = get_values(data,"channel_six", "time_distro")
# print(len(periodic1))

stochastic1 = get_values(data2,"channel_five", "time_distro")
stochastic2 = get_values(data2,"channel_three", "time_distro")
stochastic3 = get_values(data2,"channel_two", "time_distro")
stochastic4 = get_values(data2,"channel_one", "time_distro")
stochastic5 = get_values(data2,"channel_four", "time_distro")
stochastic6 = get_values(data2,"channel_six", "time_distro")

In [6]:
# shuffle the imported ideal channels
def shuffle(periodic):
    count  = 0
    i = 0
    total = 0
    full = []
    while count < len(periodic) and i < 100:
        end = 100+count
        c = periodic[count:end]
        full.append(c)
        total+=1
#         print(i)
#         print(c)
        i+=1
        count+=1
        if len(c)<100:
            break
    return full


In [9]:
pe1 =  shuffle(periodic1)
pe2 = shuffle(periodic2)
pe3 = shuffle(periodic3)
pe4 = shuffle(periodic4)
pe5 = shuffle(periodic5)
pe6 = shuffle(periodic6)
sto1 = shuffle(stochastic1)
sto2 = shuffle(stochastic2)
sto3= shuffle(stochastic3)
sto4= shuffle(stochastic4)
sto5 = shuffle(stochastic5)
sto6 = shuffle(stochastic6)

# print(len(pe5))

In [17]:
# Import the actual traffic patterns recorded over air 
dataset1 = pd.read_csv('channel_1_periodic.csv')
# print(dataset1.shape)
dataset2 = pd.read_csv('channel_2_periodic.csv')
# print(dataset2.shape)
dataset3 = pd.read_csv('channel_3_periodic.csv')
# print(dataset3.shape)
dataset4 = pd.read_csv('channel_4_stochastic.csv')
# print(dataset4.shape)
dataset5 = pd.read_csv('channel_5_stochastic.csv')
# print(dataset5.shape)
dataset6 = pd.read_csv('channel_6_stochastic.csv')
# print(dataset6.shape)
dataset2.head(100)

_id   busy
0   5fc2495cc2e41eee56af1bde   True
1   5fc24962c2e41eee56af1be8   True
2   5fc24968c2e41eee56af1bee  False
3   5fc2496ec2e41eee56af1bf4   True
4   5fc24974c2e41eee56af1bfa  False
..                       ...    ...
95  5fc24b96c2e41eee56af1e1c   True
96  5fc24b9cc2e41eee56af1e22   True
97  5fc24ba2c2e41eee56af1e28   True
98  5fc24ba8c2e41eee56af1e2e  False
99  5fc24baec2e41eee56af1e34  False

[100 rows x 2 columns]

In [18]:
# Do analysis on the data
def convertDF(dataset):
    dataset["busy"] = dataset["busy"].astype(int)
    dataset.drop('_id',
      axis='columns', inplace=True)
    return dataset



In [19]:
dataset1 = convertDF(dataset1)
dataset2 = convertDF(dataset2)
dataset3 = convertDF(dataset3)
dataset4 = convertDF(dataset4)
dataset5 = convertDF(dataset5)
dataset6 = convertDF(dataset6)


In [20]:
dataset1 = dataset1.T
dataset2 = dataset2.T
dataset3 = dataset3.T
dataset4 = dataset4.T
dataset5 = dataset5.T
dataset6 = dataset6.T
# dataset6.head()


In [21]:
data_list1 = dataset1.values.tolist()
data_list2 = dataset2.values.tolist()
data_list3 = dataset3.values.tolist()
data_list4 = dataset4.values.tolist()
data_list5 = dataset5.values.tolist()
data_list6 = dataset6.values.tolist()

# print(len(data_list6[0]))
# print(data_list6[0])

In [22]:
def to50(data):
    count  = 0
    i = 0
    total = 0
    full = []
    # print(len(periodic1))
    while count < len(data) and i < 100:
        end = 100+count
        c = data[count:end]
        full.append(c)
        total+=1
#         print(i)
#         print(c)
        i+=1
        count+=1
        if len(c)<100:
            break
    return full

In [45]:
data_list1_modified= to50(data_list1[0])
data_list2_modified= to50(data_list2[0])
data_list3_modified= to50(data_list3[0])
data_list4_modified= to50(data_list4[0])
data_list5_modified= to50(data_list5[0])
data_list6_modified= to50(data_list6[0])

print(len(data_list6_modified))
print(data_list2_modified[0])
print(data_list6_modified[0])

2
[1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0]
[1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0]


In [62]:
full_chan = []
for i in pe1:
    full_chan.append(i)
for j in pe2:
    full_chan.append(j)
    
for  k in pe3:
    full_chan.append(k)
for l in pe4:
    full_chan.append(l)
for m in pe5:
    full_chan.append(m)
for n in pe6:
    full_chan.append(n)
for o in data_list1_modified:
    full_chan.append(o)
for p in data_list2_modified:
    full_chan.append(p)
    
for q in data_list3_modified:
    full_chan.append(q)
    
print(full_chan)

[[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0], [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1], [1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,

In [77]:
dataF = pd.DataFrame(full_chan, columns = [str(i) for i in range(0,100)])
dataF = dataF.fillna(0)
dataF = dataF.astype({'99': 'int64'})
dataF.to_csv("full_periodic1.csv")
print(dataF.shape)
print(type(dataF))
dataF.head(450)


(704, 100)
<class 'pandas.core.frame.DataFrame'>


0  1  2  3  4  5  6  7  8  9  ...  90  91  92  93  94  95  96  97  98  99
0    1  1  1  1  1  0  0  0  0  0  ...   1   1   1   1   1   0   0   0   0   0
1    1  1  1  1  0  0  0  0  0  1  ...   1   1   1   1   0   0   0   0   0   1
2    1  1  1  0  0  0  0  0  1  1  ...   1   1   1   0   0   0   0   0   1   1
3    1  1  0  0  0  0  0  1  1  1  ...   1   1   0   0   0   0   0   1   1   1
4    1  0  0  0  0  0  1  1  1  1  ...   1   0   0   0   0   0   1   1   1   1
..  .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
445  1  0  0  0  0  1  1  1  1  1  ...   1   0   0   0   0   1   1   1   1   1
446  0  0  0  0  1  1  1  1  1  1  ...   0   0   0   0   1   1   1   1   1   1
447  0  0  0  1  1  1  1  1  1  0  ...   0   0   0   1   1   1   1   1   1   0
448  0  0  1  1  1  1  1  1  0  0  ...   0   0   1   1   1   1   1   1   0   0
449  0  1  1  1  1  1  1  0  0  0  ...   0   1   1   1   1   1   1   0   0   0

[450 rows x 100 columns]

In [78]:
full_chan_sto = []
for a in sto1:
    full_chan_sto.append(a)
for b in sto2:
    full_chan_sto.append(b)
for c in sto3:
    full_chan_sto.append(c)
    
for d in sto4:
    full_chan_sto.append(d)
for e in sto5:
    full_chan_sto.append(e)
for f in sto6:
    full_chan_sto.append(f)
for g in data_list4_modified:
    full_chan_sto.append(g)
    
for h in data_list5_modified:
    full_chan_sto.append(h)
for i in data_list6_modified:
    full_chan_sto.append(i)
    
# print(len(full_chan_sto))

In [79]:
dataF2 = pd.DataFrame(full_chan_sto, columns = [str(i) for i in range(0,100)])
dataF2.to_csv("full_stochastic1.csv")
dataF2 = dataF.fillna(0)
dataF2 = dataF.astype({'99': 'int64'})
print(dataF2.shape)
print(type(dataF2))
dataF2.head(450)

(704, 100)
<class 'pandas.core.frame.DataFrame'>


0  1  2  3  4  5  6  7  8  9  ...  90  91  92  93  94  95  96  97  98  99
0    1  1  1  1  1  0  0  0  0  0  ...   1   1   1   1   1   0   0   0   0   0
1    1  1  1  1  0  0  0  0  0  1  ...   1   1   1   1   0   0   0   0   0   1
2    1  1  1  0  0  0  0  0  1  1  ...   1   1   1   0   0   0   0   0   1   1
3    1  1  0  0  0  0  0  1  1  1  ...   1   1   0   0   0   0   0   1   1   1
4    1  0  0  0  0  0  1  1  1  1  ...   1   0   0   0   0   0   1   1   1   1
..  .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
445  1  0  0  0  0  1  1  1  1  1  ...   1   0   0   0   0   1   1   1   1   1
446  0  0  0  0  1  1  1  1  1  1  ...   0   0   0   0   1   1   1   1   1   1
447  0  0  0  1  1  1  1  1  1  0  ...   0   0   0   1   1   1   1   1   1   0
448  0  0  1  1  1  1  1  1  0  0  ...   0   0   1   1   1   1   1   1   0   0
449  0  1  1  1  1  1  1  0  0  0  ...   0   1   1   1   1   1   1   0   0   0

[450 rows x 100 columns]

In [80]:
channels2 = [stochastic1,stochastic2,stochastic3,stochastic4,stochastic5,stochastic6]
df2 = pd.DataFrame(channels2, columns = [str(i) for i in range(0,10000)])
df2.to_csv("stochastic.csv")
df2.head(6)

0  1  2  3  4  5  6  7  8  9  ...  9990  9991  9992  9993  9994  9995  \
0  0  0  0  0  0  0  1  0  1  1  ...     0     0     1     0     0     1   
1  1  1  0  1  0  1  1  0  0  1  ...     0     1     0     0     1     0   
2  1  0  0  0  0  0  1  0  0  0  ...     1     0     0     1     0     1   
3  0  0  0  1  1  0  1  0  1  0  ...     0     0     1     1     0     0   
4  0  1  0  0  0  0  1  0  1  0  ...     0     0     1     0     0     0   
5  0  0  0  1  0  0  0  0  0  0  ...     0     0     0     0     0     0   

   9996  9997  9998  9999  
0     0     1     0     1  
1     1     1     1     1  
2     0     0     0     1  
3     0     1     0     0  
4     0     1     1     0  
5     0     0     0     1  

[6 rows x 10000 columns]

In [81]:
df13 = df2[df2.columns[0:100]]
df14 = df2[df2.columns[100:200]]
df14.columns = [str(i) for i in range(0,100)]
df15 = df2[df2.columns[100:200]]
df15.columns = [str(i) for i in range(0,100)]
df16 = df2[df2.columns[200:300]]
df16.columns = [str(i) for i in range(0,100)]
df17 = df2[df2.columns[300:400]]
df17.columns = [str(i) for i in range(0,100)]
df18 = df2[df2.columns[400:500]]
df18.columns = [str(i) for i in range(0,100)]
df19 = df2[df2.columns[500:600]]
df19.columns = [str(i) for i in range(0,100)]
df21 = df2[df2.columns[600:700]]
df21.columns = [str(i) for i in range(0,100)]
df22 = df2[df2.columns[700:800]]
df22.columns = [str(i) for i in range(0,100)]
df23 = df2[df2.columns[800:900]]
df23.columns = [str(i) for i in range(0,100)]
print(df15.shape)
df14.head(10)

(6, 100)


0  1  2  3  4  5  6  7  8  9  ...  90  91  92  93  94  95  96  97  98  99
0  1  1  0  0  1  1  0  1  0  0  ...   0   1   0   0   0   1   0   1   0   1
1  1  1  0  0  0  1  0  0  1  0  ...   0   0   0   0   0   0   1   1   1   1
2  0  0  0  0  0  0  0  0  0  1  ...   0   0   0   0   0   0   0   0   0   0
3  0  1  1  0  1  0  0  0  0  1  ...   1   1   0   1   1   0   0   1   1   1
4  1  1  0  0  0  1  0  0  1  1  ...   0   0   0   1   0   0   1   0   0   0
5  0  0  0  0  0  1  0  0  0  0  ...   0   1   0   0   0   0   0   0   0   0

[6 rows x 100 columns]

In [82]:
df30 = pd.concat([df13,df14,df15,df16,df17,df18,df19,df21,df22,df23], ignore_index = True, axis = 0) 
print(df30.shape) 
traffic_type2 = [0 for i in range(60)]
df30["Traffic_type"] = traffic_type2
df30.head(10)

(60, 100)


0  1  2  3  4  5  6  7  8  9  ...  91  92  93  94  95  96  97  98  99  \
0  0  0  0  0  0  0  1  0  1  1  ...   1   0   0   0   0   1   1   0   1   
1  1  1  0  1  0  1  1  0  0  1  ...   1   1   0   0   1   1   0   1   1   
2  1  0  0  0  0  0  1  0  0  0  ...   0   0   0   0   0   0   0   0   0   
3  0  0  0  1  1  0  1  0  1  0  ...   1   1   1   1   0   1   1   1   0   
4  0  1  0  0  0  0  1  0  1  0  ...   1   1   0   0   0   0   1   0   1   
5  0  0  0  1  0  0  0  0  0  0  ...   0   0   0   0   0   1   0   0   0   
6  1  1  0  0  1  1  0  1  0  0  ...   1   0   0   0   1   0   1   0   1   
7  1  1  0  0  0  1  0  0  1  0  ...   0   0   0   0   0   1   1   1   1   
8  0  0  0  0  0  0  0  0  0  1  ...   0   0   0   0   0   0   0   0   0   
9  0  1  1  0  1  0  0  0  0  1  ...   1   0   1   1   0   0   1   1   1   

   Traffic_type  
0             0  
1             0  
2             0  
3             0  
4             0  
5             0  
6             0  
7             0  
8             0  
9             0  

[10 rows x 101 columns]

In [83]:
full_stochastic = df30.append(dataF2, ignore_index = True)
full_stochastic["Traffic_type"] = full_stochastic["Traffic_type"].fillna(0)
full_stochastic["Traffic_type"] = full_stochastic["Traffic_type"].astype(int)

print(full_stochastic.shape)
full_stochastic.head(410)

(764, 101)


0  1  2  3  4  5  6  7  8  9  ...  91  92  93  94  95  96  97  98  99  \
0    0  0  0  0  0  0  1  0  1  1  ...   1   0   0   0   0   1   1   0   1   
1    1  1  0  1  0  1  1  0  0  1  ...   1   1   0   0   1   1   0   1   1   
2    1  0  0  0  0  0  1  0  0  0  ...   0   0   0   0   0   0   0   0   0   
3    0  0  0  1  1  0  1  0  1  0  ...   1   1   1   1   0   1   1   1   0   
4    0  1  0  0  0  0  1  0  1  0  ...   1   1   0   0   0   0   1   0   1   
..  .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
405  1  1  0  0  0  1  1  1  1  1  ...   1   0   0   0   1   1   1   1   1   
406  1  0  0  0  1  1  1  1  1  1  ...   0   0   0   1   1   1   1   1   1   
407  0  0  0  1  1  1  1  1  1  1  ...   0   0   1   1   1   1   1   1   1   
408  0  0  1  1  1  1  1  1  1  0  ...   0   1   1   1   1   1   1   1   0   
409  0  1  1  1  1  1  1  1  0  0  ...   1   1   1   1   1   1   1   0   0   

     Traffic_type  
0               0  
1               0  
2               0  
3               0  
4               0  
..            ...  
405             0  
406             0  
407             0  
408             0  
409             0  

[410 rows x 101 columns]

In [84]:
# traffic_combined_main = pd.concat([dataF,df30], ignore_index = True, axis = 0)
traffic_combined = full_stochastic.append(dataF, ignore_index = True)
traffic_combined["Traffic_type"] = traffic_combined["Traffic_type"].fillna(1)
traffic_combined["Traffic_type"] = traffic_combined["Traffic_type"].astype(int)

print(traffic_combined.shape)
traffic_combined.head(960)

(1468, 101)


0  1  2  3  4  5  6  7  8  9  ...  91  92  93  94  95  96  97  98  99  \
0    0  0  0  0  0  0  1  0  1  1  ...   1   0   0   0   0   1   1   0   1   
1    1  1  0  1  0  1  1  0  0  1  ...   1   1   0   0   1   1   0   1   1   
2    1  0  0  0  0  0  1  0  0  0  ...   0   0   0   0   0   0   0   0   0   
3    0  0  0  1  1  0  1  0  1  0  ...   1   1   1   1   0   1   1   1   0   
4    0  1  0  0  0  0  1  0  1  0  ...   1   1   0   0   0   0   1   0   1   
..  .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
955  1  1  1  1  1  1  1  1  0  1  ...   1   1   1   1   1   1   1   0   1   
956  1  1  1  1  1  1  1  0  1  1  ...   1   1   1   1   1   1   0   1   1   
957  1  1  1  1  1  1  0  1  1  1  ...   1   1   1   1   1   0   1   1   1   
958  1  1  1  1  1  0  1  1  1  1  ...   1   1   1   1   0   1   1   1   1   
959  1  1  1  1  0  1  1  1  1  1  ...   1   1   1   0   1   1   1   1   1   

     Traffic_type  
0               0  
1               0  
2               0  
3               0  
4               0  
..            ...  
955             1  
956             1  
957             1  
958             1  
959             1  

[960 rows x 101 columns]

In [85]:
traffic_combined_shuffled = traffic_combined.sample(frac = 1).reset_index(drop = True)
print(traffic_combined_shuffled.shape)
traffic_combined_shuffled.head(79)

(1468, 101)


0  1  2  3  4  5  6  7  8  9  ...  91  92  93  94  95  96  97  98  99  \
0   0  0  0  1  1  1  1  1  0  0  ...   0   0   1   1   1   1   1   0   0   
1   0  0  1  1  0  0  1  1  1  0  ...   1   1   1   1   0   0   1   1   1   
2   0  0  1  1  0  0  0  0  0  0  ...   0   1   1   0   0   0   0   0   0   
3   0  0  1  1  1  1  1  1  1  0  ...   0   1   1   1   1   1   1   1   0   
4   1  0  0  0  0  0  1  1  1  1  ...   0   0   0   0   0   1   1   1   1   
.. .. .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
74  0  0  0  0  0  1  1  0  0  0  ...   0   0   0   0   1   1   0   0   0   
75  1  0  1  0  1  1  1  0  0  1  ...   1   0   0   1   1   1   0   1   1   
76  0  0  0  0  1  1  1  1  1  1  ...   0   0   0   1   1   1   1   1   1   
77  1  1  1  1  1  1  1  1  1  0  ...   1   1   1   1   1   1   1   1   0   
78  1  1  0  0  0  0  1  1  1  1  ...   1   0   0   0   0   1   1   1   1   

    Traffic_type  
0              1  
1              1  
2              1  
3              0  
4              1  
..           ...  
74             1  
75             1  
76             0  
77             0  
78             0  

[79 rows x 101 columns]

In [86]:
traffic_combined.to_csv("traffic_patterns.csv")
traffic_combined_shuffled.to_csv("shuffled_traffic_patterns.csv")

In [87]:
dataset = pd.read_csv('shuffled_traffic_patterns.csv')
# print(dataset.shape)

In [88]:
X = dataset.iloc[:, 1:101].values
print(X)
print(X.shape)
y = dataset.iloc[:, -1].values
print(y)

[[0 0 0 ... 1 0 0]
 [0 0 1 ... 1 1 1]
 [0 0 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 1 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 0]]
(1468, 100)
[1 1 1 ... 1 0 0]


In [89]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)
print(X_train.shape)

(1101, 100)


In [90]:
# Training the Kernel SVM model on the Training set
from sklearn.svm import SVC
classifier1 = SVC(kernel = 'rbf', random_state = 0)
classifier1.fit(X_train, y_train)

from sklearn.naive_bayes import GaussianNB
classifier2 = GaussianNB()
classifier2.fit(X_train, y_train)

# Training the Random Forest Classification model on the Training set
from sklearn.ensemble import RandomForestClassifier
classifier3 = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier3.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [91]:
# Predicting the Test set results
y_pred = classifier1.predict(X_test)
print(y_pred)
y_pred2 = classifier2.predict(X_test)
print(y_pred2)
y_pred3 = classifier3.predict(X_test)
print(y_pred3)

[0 0 0 1 0 0 1 1 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 0 1 1 0 1 0 1 1 0 0 1 1 1 0
 0 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0 1 1 0 1 0
 0 1 1 0 0 1 0 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 1 0
 0 0 1 0 0 0 1 1 0 1 1 0 1 1 1 1 0 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 1 0 1 0 1
 1 1 0 1 1 0 0 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 1 1 1 0 1 1 0 0 0 0 0
 1 0 0 1 0 0 0 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 0 1 1 1 0 1 0
 0 1 1 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 1 1 0 0 1 1 0 1 1
 1 0 1 0 1 1 1 1 1 0 1 1 0 0 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0 0
 0 0 1 1 1 0 0 1 1 0 0 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 0
 0 1 0 0 1 0 1 1 1 0 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 1]
[0 0 1 1 1 1 1 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1
 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 0
 1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1
 0 1 1 1 0 0 1 1 0 0 1 1 0 1 1

In [92]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred)
print(cm1)
cm2 = confusion_matrix(y_test, y_pred2)
print(cm2)
cm3 = confusion_matrix(y_test, y_pred3)
print(cm3)

[[ 68 140]
 [ 96  63]]
[[ 96 112]
 [ 81  78]]
[[ 66 142]
 [ 92  67]]


In [93]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score, precision_score
recall = recall_score(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy)
print(precision)
print(recall)

[[ 68 140]
 [ 96  63]]
0.3569482288828338
0.3103448275862069
0.39622641509433965


In [94]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score, precision_score
recall = recall_score(y_test,y_pred3)
accuracy = accuracy_score(y_test,y_pred3)
precision = precision_score(y_test,y_pred3)
cm = confusion_matrix(y_test, y_pred3)
print(cm)
print(accuracy)
print(precision)
print(recall)

[[ 66 142]
 [ 92  67]]
0.36239782016348776
0.32057416267942584
0.42138364779874216


In [95]:
check1 = df18.iloc[0:1, :].values
print(check1)
check2 = df21.iloc[0:1, :].values
print(check2)



[[0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0 0
  0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1 0
  0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1]]
[[1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0
  0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 1 0 1 0 0 0
  0 1 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0]]


In [96]:
class1 = classifier1.predict(check1)
print(class1)
class2 = classifier1.predict(check2)
print(class2)

[0]
[0]


In [97]:
# Testing starts hereee
da1 = pd.read_csv('channel_2_periodic.csv')
print(da1.shape)

(616, 2)


In [98]:
da1["busy"] = da1["busy"].astype(int)
da1.drop('_id',
  axis='columns', inplace=True)
da1.head(2)

busy
0     1
1     1

In [99]:
da2 = da1.T
da2.head()

0    1    2    3    4    5    6    7    8    9    ...  606  607  608  \
busy    1    1    0    1    0    1    1    0    1    0  ...    1    1    0   

      609  610  611  612  613  614  615  
busy    0    1    1    1    0    0    1  

[1 rows x 616 columns]

In [100]:
da_list = da2.values.tolist()
print(len(da_list[0]))

616


In [71]:
def change(periodic):
    count  = 0
    i = 0
    total = 0
    full = []
    # print(len(periodic1))
    while count < len(periodic) and i < 100:
        end = 100+count
        c = periodic[count:end]
        full.append(c)
        total+=1
#         print(i)
#         print(c)
        i+=1
        count+=1
        if len(c)<100:
            break
    return full

In [72]:
d = change(da_list[0])
print(len(d[0]))
print(d[0])

100
[1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0]


In [73]:
def classifier(input):
    input = input.tolist()
    count = 0
#     print(input)
    if len(input) == 100:
        input = list([input])
#         print(input)
        for i in input[0]:
            if i == 1:
                count+=1
    else:
        for i in input[0]:
            if i == 1:
                count+=1
    classify = classifier3.predict(input)
    return count, classify

chh = classifier(np.array(d[23]))
print(chh)

(66, array([0], dtype=int64))


In [74]:
def classifier(input):
    input = input.tolist()
    count = 0
#     print(input)
    if len(input) == 100:
        input = list([input])
#         print(input)
        for i in input[0]:
            if i == 1:
                count+=1
    else:
        for i in input[0]:
            if i == 1:
                count+=1
    classify = classifier1.predict(input)
    return count, classify

chh = classifier(np.array(data_list1_modified[9]))
print(chh)

(30, array([0], dtype=int64))


In [82]:
# save model to file
import pickle
pickle.dump(classifier3,open("traffic_classification.pkl", "wb"),protocol=2)
# with open('model.pkl', 'wb') as model_file:
#   pickle.dump(classifier, model_file)

In [83]:
# pickle.dump( {'train_x':X_train, 'train_y':y_train}, open( "traffic_classification_data.pkl", "wb" ) )

In [84]:
with open(f'traffic_classification.pkl', 'rb') as f:
    model1 = pickle.load(f)

In [85]:
sequence = data_list1_modified[10]
print(len(sequence
         ))
print(sequence)

100
[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]


In [86]:
input_data = pd.DataFrame([sequence], dtype=int)
# print(input_data)
results = model1.predict([sequence])[0]
print(results)

0
